[package]
name = "duplicity"
version = "0.1.0"
authors = ["Jorge Martí <jormarma@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
hex = "0.4.3"
sha2 = "0.10.8"
